### ISSUE TITLE
undefined reference to `SocketServer::SocketServer(int, std::string)'

### ISSUE THREAD

**Issue by friyadhibiermann** [alexanderkoumis/toy-opencv-mat-socket-server#3]
<li><strong>Makefile</strong></li>
<pre>
# Copyright (C) 2014 WRTnode machine team.
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#
# noel<noel@wrtnode.com>
#

include $(TOPDIR)/rules.mk

PKG_NAME:=cv_server
PKG_RELEASE:=1

PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)
PKG_INSTALL_DIR:=$(PKG_BUILD_DIR)/ipkg-install

include $(INCLUDE_DIR)/kernel.mk
include $(INCLUDE_DIR)/package.mk

define Package/cv_server
  SECTION:=opencv
  CATEGORY:=opencv_socket
  SUBMENU :=demos
  TITLE:=opencv demo app
  DEPENDS := +opencv
endef

define Package/cv_server/description
        openWRT test program for opencv lib
endef

define Build/Prepare
        mkdir -p $(PKG_BUILD_DIR)
        $(CP) ./src/* $(PKG_BUILD_DIR)/
endef

define Build/Compile
        $(MAKE) -C $(PKG_BUILD_DIR) \
                $(TARGET_CONFIGURE_OPTS) \
                LDFLAGS="$(TARGET_LDFLAGS)" \
                CFLAGS="$(TARGET_CFLAGS)"

endef

define Package/cv_server/install
        $(INSTALL_DIR) $(1)/usr/bin
        $(INSTALL_BIN) $(PKG_BUILD_DIR)/cv_server $(1)/usr/bin/
endef

$(eval $(call BuildPackage,cv_server))
</pre>
<li><strong>src/Makefile</strong></li>
<pre>
PROGS     = cv_server
INSTDIR   = $(prefix)/usr/bin
INSTMODE  = 0755
INSTOWNER = root
INSTGROUP = root

OBJS = cv_server.o
LDLIBS += -lm -lopencv_core -lopencv_highgui \
           -lopencv_imgcodecs -lopencv_videoio

all: $(PROGS)
$(PROGS): $(OBJS)
        $(CXX) -Wextra -Werror -std=c++11 $(CFLAGS) $(LDFLAGS) $^ $(LDLIBS) -o $@

%.o: %.cpp
        $(CXX) -c $(CFLAGS) -Wextra -Werror -std=c++11 $^ -o $@

install: $(PROGS)
        $(INSTALL) -d $(INSTDIR)
        $(INSTALL) -m $(INSTMODE) -o $(INSTOWNER) -g $(INSTGROUP) $(PROGS) $(INSTDIR)

clean:
        rm -f $(PROGS) *.o
</pre>
<li><strong>list file src/</strong></li>
<pre>
cv_server.cpp  Makefile  socket_server.cpp  socket_server.hpp
</pre>
<li><strong>error log compile</strong></li>
<pre>
make -C /home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server AR="arm-openwrt-linux-uclibcgnueabi-gcc-ar" AS="arm-openwrt-linux-uclibcgnueabi-gcc -c -Os -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard" LD=arm-openwrt-linux-uclibcgnueabi-ld NM="arm-openwrt-linux-uclibcgnueabi-gcc-nm" CC="arm-openwrt-linux-uclibcgnueabi-gcc" GCC="arm-openwrt-linux-uclibcgnueabi-gcc" CXX="arm-openwrt-linux-uclibcgnueabi-g++" RANLIB="arm-openwrt-linux-uclibcgnueabi-gcc-ranlib" STRIP=arm-openwrt-linux-uclibcgnueabi-strip OBJCOPY=arm-openwrt-linux-uclibcgnueabi-objcopy OBJDUMP=arm-openwrt-linux-uclibcgnueabi-objdump SIZE=arm-openwrt-linux-uclibcgnueabi-size LDFLAGS="-L/home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/usr/lib -L/home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/lib -L/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/lib -L/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/lib" CFLAGS="-Os -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard"
make[4]: Entering directory '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server'
arm-openwrt-linux-uclibcgnueabi-g++ -c -Os -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -Wextra -Werror -std=c++11 cv_server.cpp -o cv_server.o
arm-openwrt-linux-uclibcgnueabi-g++ -Wextra -Werror -std=c++11 -Os -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -L/home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/usr/lib -L/home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/lib -L/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/lib -L/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/lib cv_server.o -lm -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_videoio -o cv_server
cv_server.o: In function `main':
cv_server.cpp:(.text.startup+0x40): undefined reference to `SocketServer::SocketServer(int, std::string)'
cv_server.cpp:(.text.startup+0x50): undefined reference to `SocketServer::ConnectToNetwork()'
cv_server.cpp:(.text.startup+0x58): undefined reference to `SocketServer::ReceiveImageDims()'
cv_server.cpp:(.text.startup+0xb0): undefined reference to `SocketServer::ReceiveImage(cv::Mat&)'
cv_server.cpp:(.text.startup+0xbc): undefined reference to `SocketServer::WriteImage(cv::Mat&)'
collect2: error: ld returned 1 exit status
Makefile:14: recipe for target 'cv_server' failed
make[4]: *** [cv_server] Error 1
make[4]: Leaving directory '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server'
</pre>

**Comment by alexanderkoumis** [comment]
I'm going to leave this one to you to figure out, this is an error in your own build process. If you use cmake to build the provided example program it will compile.
