### ISSUE TITLE
error: 'to_string' is not a member of 'std' 

### ISSUE THREAD

**Issue by friyadhibiermann** [alexanderkoumis/toy-opencv-mat-socket-server#4]
<li>Makefile</li>
<pre>
# Copyright (C) 2014 WRTnode machine team.
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#
# noel<noel@wrtnode.com>
#

include $(TOPDIR)/rules.mk

PKG_NAME:=cv_server
PKG_RELEASE:=1

PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)
PKG_INSTALL_DIR:=$(PKG_BUILD_DIR)/ipkg-install

include $(INCLUDE_DIR)/kernel.mk
include $(INCLUDE_DIR)/package.mk

define Package/cv_server
  SECTION:=wrtnode
  CATEGORY:=WRTnode
  SUBMENU :=demos
  TITLE:=opencv demo app
  DEPENDS := +opencv
endef

define Package/cv_server/description
	WRTnode test program for opencv lib
endef

define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)
	$(CP) ./src/* $(PKG_BUILD_DIR)/
endef

define Build/Configure
	IN_OPENWRT=1 \
	AR="$(TOOLCHAIN_DIR)/bin/$(TARGET_CROSS)ar" \
	AS="$(TOOLCHAIN_DIR)/bin/$(TARGET_CC) -c $(TARGET_CFLAGS)" \
	LD="$(TOOLCHAIN_DIR)/bin/$(TARGET_CROSS)ld" \
	NM="$(TOOLCHAIN_DIR)/bin/$(TARGET_CROSS)nm" \
	CC="$(TOOLCHAIN_DIR)/bin/$(TARGET_CC)" \
	GCC="$(TOOLCHAIN_DIR)/bin/$(TARGET_CC)" \
	CXX="$(TOOLCHAIN_DIR)/bin/$(TARGET_CROSS)g++" \
	RANLIB="$(TOOLCHAIN_DIR)/bin/$(TARGET_CROSS)ranlib" \
	STRIP="$(TOOLCHAIN_DIR)/bin/$(TARGET_CROSS)strip" \
	OBJCOPY="$(TOOLCHAIN_DIR)/bin/$(TARGET_CROSS)objcopy" \
	OBJDUMP="$(TOOLCHAIN_DIR)/bin/$(TARGET_CROSS)objdump" \
	TARGET_CPPFLAGS="$(TARGET_CPPFLAGS)" \
	TARGET_CFLAGS="$(TARGET_CFLAGS)" \
	TARGET_LDFLAGS="$(TARGET_LDFLAGS)" \
	CMAKE_CXX_FLAGS="$(CMAKE_CXX_FLAGS) -std=c++11"
	CMAKE_SYSTEM_NAME="Linux"
	CMAKE_C_COMPILER="arm-openwrt-linux-uclibc-gcc"
	CMAKE_SYSTEM_PROCESSOR="armv7-a"
	CMAKE_CXX_COMPILER="arm-openwrt-linux-uclibc-g++"
	CMAKE_FIND_ROOT_PATH="${HOME}/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/"
	cmake $(PKG_BUILD_DIR)/CMakeLists.txt
endef

define Build/Compile
	$(MAKE) -C $(PKG_BUILD_DIR) \
		$(TARGET_CONFIGURE_OPTS) \
		LDFLAGS="$(TARGET_LDFLAGS)" \
		CFLAGS="$(TARGET_CFLAGS) -Wextra -Werror -std=c++11"

endef

define Package/cv_server/install
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/cv_server $(1)/usr/bin/
endef

$(eval $(call BuildPackage,cv_server))
</pre>
<li>src/CMakeList.txt</li>
<pre>
cmake_minimum_required(VERSION 2.8)
project(cv_server)

find_package(OpenCV 3 REQUIRED)

set(CMAKE_CXX_FLAGS "-std=c++11")
set(IN_OPENWRT 1)
set(AR "${TOOLCHAIN_DIR}/bin/${TARGET_CROSS}ar")
set(AS "${TOOLCHAIN_DIR}/bin/${TARGET_CC} -c ${TARGET_CFLAGS}")
set(LD "${TOOLCHAIN_DIR}/bin/${TARGET_CROSS}ld"})
set(NM "${TOOLCHAIN_DIR}/bin/${TARGET_CROSS}nm")
set(CC "${TOOLCHAIN_DIR}/bin/${TARGET_CC}")
set(GCC "${TOOLCHAIN_DIR}/bin/${TARGET_CC}")
set(CXX "${TOOLCHAIN_DIR}/bin/${TARGET_CROSS}g++")
set(RANLIB "${TOOLCHAIN_DIR}/bin/${TARGET_CROSS}ranlib")
set(STRIP "${TOOLCHAIN_DIR}/bin/$(TARGET_CROSS)strip")
set(OBJCOPY "${TOOLCHAIN_DIR}/bin/${TARGET_CROSS}objcopy")
set(OBJDUMP "${TOOLCHAIN_DIR}/bin/${TARGET_CROSS}objdump")
set(TARGET_CPPFLAGS "${TARGET_CPPFLAGS}")
set(TARGET_CFLAGS "${TARGET_CFLAGS}")
set(TARGET_LDFLAGS "${TARGET_LDFLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_C_COMPILER "/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-gcc")
set(CMAKE_SYSTEM_PROCESSOR "armv7-a")
set(CMAKE_CXX_COMPILER "/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-g++")
include_directories(
	
  ${CMAKE_CURRENT_SOURCE_DIR}
  ${OpenCV_INCLUDE_DIRS}
)

add_executable(sample_server
  sample/sample_server.cpp
  socket_server.cpp
)

add_executable(sample_client
  sample/sample_client.cpp
  socket_client.cpp
)

target_link_libraries(sample_server ${OpenCV_LIBS})
target_link_libraries(sample_client ${OpenCV_LIBS})
</pre>
<li>debug</li>
<pre>
make[1]: Entering directory '/home/opiz/openwrt'
make[2]: Entering directory '/home/opiz/openwrt/package/libs/toolchain'
if [ -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean ]; then rm -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean; fi; echo "libc" >> /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install
if [ -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean ]; then rm -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean; fi; echo "libgcc" >> /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install
if [ -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean ]; then rm -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean; fi; echo "libstdcpp" >> /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install
if [ -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean ]; then rm -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean; fi; echo "libpthread" >> /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install
if [ -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean ]; then rm -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean; fi; echo "librt" >> /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install
make[2]: Leaving directory '/home/opiz/openwrt/package/libs/toolchain'
make[2]: Entering directory '/home/opiz/openwrt/package/libs/zlib'
if [ -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/zlib.default.install.clean ]; then rm -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/zlib.default.install /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/zlib.default.install.clean; fi; echo "zlib" >> /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/zlib.default.install
make[2]: Leaving directory '/home/opiz/openwrt/package/libs/zlib'
make[2]: Entering directory '/home/opiz/openwrt/package/openwrt-packages/libs/opencv'
if [ -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/opencv.default.install.clean ]; then rm -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/opencv.default.install /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/opencv.default.install.clean; fi; echo "opencv" >> /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/pkginfo/opencv.default.install
make[2]: Leaving directory '/home/opiz/openwrt/package/openwrt-packages/libs/opencv'
make[2]: Entering directory '/home/opiz/openwrt/package/socket-server'
mkdir -p /home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server
cp -fpR ./src/* /home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server/
touch /home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server/.prepared_bc3a5aeafd920f19ba768a70b79eb05f
rm -f /home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/stamp/.cv_server_installed
IN_OPENWRT=1 AR="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-ar" AS="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-gcc -c -Os -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard" LD="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-ld" NM="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-nm" CC="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-gcc" GCC="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-gcc" CXX="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-g++" RANLIB="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-ranlib" STRIP="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-strip" OBJCOPY="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-objcopy" OBJDUMP="/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-objdump" TARGET_CPPFLAGS="-I/home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/usr/include -I/home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/include -I/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/include -I/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/include" TARGET_CFLAGS="-Os -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard" TARGET_LDFLAGS="-L/home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/usr/lib -L/home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/lib -L/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/lib -L/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/lib" cmake /home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server/CMakeLists.txt
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-gcc
-- Check for working C compiler: /home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-g++
-- Check for working CXX compiler: /home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-uclibcgnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server
rm -f /home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server/.configured_*
touch /home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server/.configured_yyyy
make -C /home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server AR="arm-openwrt-linux-uclibcgnueabi-gcc-ar" AS="arm-openwrt-linux-uclibcgnueabi-gcc -c -Os -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard" LD=arm-openwrt-linux-uclibcgnueabi-ld NM="arm-openwrt-linux-uclibcgnueabi-gcc-nm" CC="arm-openwrt-linux-uclibcgnueabi-gcc" GCC="arm-openwrt-linux-uclibcgnueabi-gcc" CXX="arm-openwrt-linux-uclibcgnueabi-g++" RANLIB="arm-openwrt-linux-uclibcgnueabi-gcc-ranlib" STRIP=arm-openwrt-linux-uclibcgnueabi-strip OBJCOPY=arm-openwrt-linux-uclibcgnueabi-objcopy OBJDUMP=arm-openwrt-linux-uclibcgnueabi-objdump SIZE=arm-openwrt-linux-uclibcgnueabi-size LDFLAGS="-L/home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/usr/lib -L/home/opiz/openwrt/staging_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/lib -L/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/lib -L/home/opiz/openwrt/staging_dir/toolchain-arm_cortex-a8+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/lib"<br> CFLAGS="-Os -pipe -march=armv7-a -mtune=cortex-a8 -mfpu=vfpv3-d16 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -Wextra -Werror -std=c++11"
make[3]: Entering directory '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server'
make[4]: Entering directory '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server'
make[5]: Entering directory '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server'
Scanning dependencies of target sample_client
make[5]: Leaving directory '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server'
make[5]: Entering directory '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server'
[ 25%] Building CXX object CMakeFiles/sample_client.dir/sample/sample_client.cpp.o
[ 50%] Building CXX object CMakeFiles/sample_client.dir/socket_client.cpp.o
<strong>/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server/socket_client.cpp:<br><strong> In member function 'void SocketClient::ConnectToServer()':</strong>
/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server/socket_client.cpp:29:30:<br> error: 'to_string' is not a member of 'std'
   if (getaddrinfo(hostname_, std::to_string(port_).c_str(),
</strong>                              ^
CMakeFiles/sample_client.dir/build.make:80: recipe for target 'CMakeFiles/sample_client.dir/socket_client.cpp.o' failed
make[5]: *** [CMakeFiles/sample_client.dir/socket_client.cpp.o] Error 1
make[5]: Leaving directory '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server'
CMakeFiles/Makefile2:63: recipe for target 'CMakeFiles/sample_client.dir/all' failed
make[4]: *** [CMakeFiles/sample_client.dir/all] Error 2
make[4]: Leaving directory '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server'
Makefile:75: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server'
Makefile:70: recipe for target '/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server/.built' failed
make[2]: *** [/home/opiz/openwrt/build_dir/target-arm_cortex-a8+vfpv3_uClibc-0.9.33.2_eabi/cv_server/.built] Error 2
make[2]: Leaving directory '/home/opiz/openwrt/package/socket-server'
package/Makefile:191: recipe for target 'package/socket-server/compile' failed
make[1]: *** [package/socket-server/compile] Error 2
make[1]: Leaving directory '/home/opiz/openwrt'
/home/opiz/openwrt/include/toplevel.mk:181: recipe for target 'package/socket-server/compile' failed
make: *** [package/socket-server/compile] Error 2
</pre>

**Comment by alexanderkoumis** [comment]
Please only open issues against the code I provided in the repository.
